package com.github.baymin.axis2.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-28T16:45:48.830+08:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "nameService",
                  wsdlLocation = "http://localhost:8889/services/nameService?wsdl",
                  targetNamespace = "http://webservice.axis2.baymin.github.com")
public class NameService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.axis2.baymin.github.com", "nameService");
    public final static QName NameServiceHttpSoap11Endpoint = new QName("http://webservice.axis2.baymin.github.com", "nameServiceHttpSoap11Endpoint");
    public final static QName NameServiceHttpEndpoint = new QName("http://webservice.axis2.baymin.github.com", "nameServiceHttpEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8889/services/nameService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NameService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8889/services/nameService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NameService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NameService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NameService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public NameService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NameService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NameService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns NameServicePortType
     */
    @WebEndpoint(name = "nameServiceHttpSoap11Endpoint")
    public NameServicePortType getNameServiceHttpSoap11Endpoint() {
        return super.getPort(NameServiceHttpSoap11Endpoint, NameServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NameServicePortType
     */
    @WebEndpoint(name = "nameServiceHttpSoap11Endpoint")
    public NameServicePortType getNameServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(NameServiceHttpSoap11Endpoint, NameServicePortType.class, features);
    }


    /**
     *
     * @return
     *     returns NameServicePortType
     */
    @WebEndpoint(name = "nameServiceHttpEndpoint")
    public NameServicePortType getNameServiceHttpEndpoint() {
        return super.getPort(NameServiceHttpEndpoint, NameServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NameServicePortType
     */
    @WebEndpoint(name = "nameServiceHttpEndpoint")
    public NameServicePortType getNameServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(NameServiceHttpEndpoint, NameServicePortType.class, features);
    }

}
