package com.github.baymin.axis2.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-28T16:45:48.770+08:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://webservice.axis2.baymin.github.com", name = "nameServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface NameServicePortType {


    @WebMethod(action = "urn:getName")
    @Action(input = "urn:getName", output = "urn:getNameResponse")
    @RequestWrapper(localName = "getName", targetNamespace = "http://webservice.axis2.baymin.github.com", className = "com.github.baymin.axis2.webservice.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://webservice.axis2.baymin.github.com", className = "com.github.baymin.axis2.webservice.GetNameResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.axis2.baymin.github.com")
    public String getName(

            @WebParam(name = "name", targetNamespace = "http://webservice.axis2.baymin.github.com")
                    String name
    );
}
